### ISSUE TITLE
m0 polkadot release tracking

### ISSUE THREAD

**Issue by flipchan** [XcmSend/app#19]
# Release polkadot-m0 

### New Features: 
- Swaps - supporting latest Hydradx Omnipool asset swaps in main UI and in API 
- Updated styling in the user interface 
- Fixed XCM transfer bugs
- Added support for webhooks 
- Support for http requests
- Support latest Galatic council(HydraDx) sdk
- Pill nodes 
- Better and new api(api.bagpipes.io|https://github.com/XcmSend/api) features
- New license for long term sustainability for Bagpipes
- Better template and sharing scenario functions
- Discord bot 
- Better CI and stability checking for new pull requests on github 
- Added sidebar
- Updated toolbar

## Check out the latest version in your browser:  
https://alpha.bagpipes.io

**Comment by decentration** [comment]
M0 delivered plus bonus features such as Bagpipes Discord Bot v0, improved API features, and added stable pool swaps for HydraDx.

**Comment by flipchan** [comment]
HydraDX: We now support all pools on HydraDX not only the omnipool,

**Comment by flipchan** [comment]
https://hub.docker.com/layers/xcmsend/xcmsend/v0.1.0/images/sha256-090e53bae8c3a50abb1c77fc2ab2939e878b9e76e8b998eebb6dc0ce6babb506?context=repo

**Comment by flipchan** [comment]
The BagPipe license: 
https://github.com/XcmSend/app/issues/20

**Comment by flipchan** [comment]
https://github.com/XcmSend/app/releases/tag/v0.1.0-m0
