### ISSUE TITLE
Kusama and its Asset Hub do not list any assets

### ISSUE THREAD

**Issue by DrW3RK** [XcmSend/app#25]
When selecting Kusama or its Asset Hub, none of the assets appear in the dropdown. It works as expected for Polkadot and its Asset Hub.

<img width="406" alt="image" src="https://github.com/XcmSend/app/assets/86818441/32f75032-b000-4ba6-9e81-6b778e03b52f">

**Comment by flipchan** [comment]
@DrW3RK Thank you for the issue, i will look into this

**Comment by flipchan** [comment]
live at app.xcmsend.com
